import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

interface ExportParams {
  data: any[];
  filename: string;
  title: string;
  headers: string[];
  generatedBy?: string;
  branding?: {
    portal_name?: string;
    logo_url?: string;
    hero_title?: string;
    hero_subtitle?: string;
  };
}

export const exportToPDF = ({ data, filename, title, headers, generatedBy, branding }: ExportParams) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  
  // 1. Header / Letterhead
  doc.setFillColor(26, 58, 92); // Primary color #1a3a5c
  doc.rect(0, 0, pageWidth, 40, 'F');
  
  doc.setTextColor(255, 255, 255);
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.text(branding?.hero_title || 'GOVERNMENT DELIVERY UNIT (GDU)', pageWidth / 2, 15, { align: 'center' });
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.text(branding?.hero_subtitle || 'KOGI STATE GOVERNMENT', pageWidth / 2, 22, { align: 'center' });
  
  doc.setFontSize(12);
  doc.text(branding?.portal_name || 'GDU Staff Portal', pageWidth / 2, 32, { align: 'center' });

  // 2. Report Title & Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title.toUpperCase(), 14, 55);
  
  doc.setFontSize(9);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${format(new Date(), 'PPP p')}`, 14, 62);
  if (generatedBy) {
    doc.text(`Generated by: ${generatedBy}`, 14, 67);
  }

  // 3. Table
  const tableData = data.map(row => headers.map(h => {
    // Try to find the value by header name (lowercased/underscored) or direct mapping
    const key = h.toLowerCase().replace(/\s+/g, '_');
    return row[key] || row[h] || '';
  }));

  (doc as any).autoTable({
    startY: 75,
    head: [headers],
    body: tableData,
    theme: 'grid',
    headStyles: { 
      fillColor: [26, 58, 92], 
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center'
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250]
    },
    styles: {
      fontSize: 8,
      cellPadding: 3
    },
    margin: { top: 45 }
  });

  // 4. Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `Page ${i} of ${pageCount} — GDU Staff Portal Report`,
      pageWidth / 2,
      doc.internal.pageSize.getHeight() - 10,
      { align: 'center' }
    );
    
    // Signature area on last page
    if (i === pageCount) {
      const finalY = (doc as any).lastAutoTable.finalY + 30;
      if (finalY < doc.internal.pageSize.getHeight() - 40) {
        doc.line(14, finalY, 70, finalY);
        doc.text('Authorized Signature', 14, finalY + 5);
        
        doc.line(pageWidth - 70, finalY, pageWidth - 14, finalY);
        doc.text('Date', pageWidth - 70, finalY + 5);
      }
    }
  }

  doc.save(`${filename}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export const exportToExcel = ({ data, filename, title, branding }: Omit<ExportParams, 'headers'>) => {
  // Add metadata rows at the top
  const metadata = [
    [branding?.hero_title || 'GOVERNMENT DELIVERY UNIT (GDU)'],
    [branding?.hero_subtitle || 'KOGI STATE GOVERNMENT'],
    [title],
    [`Generated on: ${format(new Date(), 'PPP p')}`],
    []
  ];

  const worksheet = XLSX.utils.json_to_sheet(data, { origin: 'A6' });
  XLSX.utils.sheet_add_aoa(worksheet, metadata, { origin: 'A1' });
  
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
  
  XLSX.writeFile(workbook, `${filename}_${format(new Date(), 'yyyyMMdd')}.xlsx`);
};

export const exportToCSV = ({ data, filename }: Omit<ExportParams, 'title' | 'headers' | 'branding'>) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csv = XLSX.utils.sheet_to_csv(worksheet);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${format(new Date(), 'yyyyMMdd')}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
