import jsPDF from 'jspdf';
import 'jspdf-autotable';
import * as XLSX from 'xlsx';
import { format } from 'date-fns';

interface ExportParams {
  data: any[];
  filename: string;
  title: string;
  headers: string[];
  generatedBy?: string;
  branding?: {
    portal_name?: string;
    logo_url?: string;
    hero_title?: string;
    hero_subtitle?: string;
  };
}

export const exportToPDF = ({ data, filename, title, headers, generatedBy, branding }: ExportParams) => {
  const doc = new jsPDF();
  const pageWidth = doc.internal.pageSize.getWidth();
  const pageHeight = doc.internal.pageSize.getHeight();
  
  // 1. Header / Letterhead
  // Add a nice top border
  doc.setFillColor(26, 58, 92); // GDU Blue
  doc.rect(0, 0, pageWidth, 5, 'F');

  // Try to add logo
  let logoY = 15;
  try {
    // We can use a default logo if branding one is missing
    const logoUrl = branding?.logo_url || '/logo.png';
    // Note: In a real browser environment, we'd need to ensure the image is loaded
    // For this implementation, we'll assume the logo is available or skip gracefully
    // doc.addImage(logoUrl, 'PNG', pageWidth / 2 - 15, logoY, 30, 30);
    // logoY += 35;
  } catch (e) {
    console.warn('Logo could not be added to PDF');
  }

  doc.setTextColor(26, 58, 92);
  doc.setFontSize(22);
  doc.setFont('helvetica', 'bold');
  doc.text('GOVERNANCE DELIVERY UNIT (GDU)', pageWidth / 2, logoY + 10, { align: 'center' });
  
  doc.setFontSize(14);
  doc.setFont('helvetica', 'bold');
  doc.setTextColor(100, 100, 100);
  doc.text('KOGI STATE GOVERNMENT', pageWidth / 2, logoY + 18, { align: 'center' });
  
  doc.setDrawColor(200, 200, 200);
  doc.line(20, logoY + 25, pageWidth - 20, logoY + 25);

  // 2. Report Title & Info
  doc.setTextColor(0, 0, 0);
  doc.setFontSize(16);
  doc.setFont('helvetica', 'bold');
  doc.text(title.toUpperCase(), 14, logoY + 40);
  
  doc.setFontSize(10);
  doc.setFont('helvetica', 'normal');
  doc.setTextColor(100, 100, 100);
  doc.text(`Generated on: ${format(new Date(), 'PPP p')}`, 14, logoY + 47);
  if (generatedBy) {
    doc.text(`Generated by: ${generatedBy}`, 14, logoY + 53);
  }

  // 3. Table
  const tableData = data.map(row => headers.map(h => {
    const key = h.toLowerCase().replace(/\s+/g, '_');
    return row[key] || row[h] || '—';
  }));

  (doc as any).autoTable({
    startY: logoY + 60,
    head: [headers],
    body: tableData,
    theme: 'grid',
    headStyles: { 
      fillColor: [26, 58, 92], 
      textColor: [255, 255, 255],
      fontStyle: 'bold',
      halign: 'center',
      fontSize: 10
    },
    alternateRowStyles: {
      fillColor: [245, 247, 250]
    },
    styles: {
      fontSize: 9,
      cellPadding: 4,
      valign: 'middle'
    },
    margin: { top: 20, left: 14, right: 14 }
  });

  // 4. Footer
  const pageCount = (doc as any).internal.getNumberOfPages();
  for (let i = 1; i <= pageCount; i++) {
    doc.setPage(i);
    
    // Page border
    doc.setDrawColor(230, 230, 230);
    doc.rect(5, 5, pageWidth - 10, pageHeight - 10);

    doc.setFontSize(8);
    doc.setTextColor(150, 150, 150);
    doc.text(
      `© ${new Date().getFullYear()} Governance Delivery Unit (GDU) — Kogi State Government`,
      14,
      pageHeight - 10
    );
    doc.text(
      `Page ${i} of ${pageCount}`,
      pageWidth - 30,
      pageHeight - 10
    );
  }

  doc.save(`${filename}_${format(new Date(), 'yyyyMMdd')}.pdf`);
};

export const exportToExcel = ({ data, filename, title, branding }: Omit<ExportParams, 'headers'>) => {
  // Add metadata rows at the top
  const metadata = [
    ['GOVERNANCE DELIVERY UNIT (GDU)'],
    ['KOGI STATE GOVERNMENT'],
    [title.toUpperCase()],
    [`Generated on: ${format(new Date(), 'PPP p')}`],
    []
  ];

  const worksheet = XLSX.utils.json_to_sheet(data, { origin: 'A6' });
  XLSX.utils.sheet_add_aoa(worksheet, metadata, { origin: 'A1' });
  
  const workbook = XLSX.utils.book_new();
  XLSX.utils.book_append_sheet(workbook, worksheet, "Report");
  
  XLSX.writeFile(workbook, `${filename}_${format(new Date(), 'yyyyMMdd')}.xlsx`);
};

export const exportToCSV = ({ data, filename }: Omit<ExportParams, 'title' | 'headers' | 'branding'>) => {
  const worksheet = XLSX.utils.json_to_sheet(data);
  const csv = XLSX.utils.sheet_to_csv(worksheet);
  const blob = new Blob([csv], { type: 'text/csv;charset=utf-8;' });
  const link = document.createElement("a");
  const url = URL.createObjectURL(blob);
  link.setAttribute("href", url);
  link.setAttribute("download", `${filename}_${format(new Date(), 'yyyyMMdd')}.csv`);
  link.style.visibility = 'hidden';
  document.body.appendChild(link);
  link.click();
  document.body.removeChild(link);
};
