/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DashboardIndexRouteImport } from './routes/dashboard/index'
import { Route as DashboardStaffRouteImport } from './routes/dashboard/staff'
import { Route as DashboardSettingsRouteImport } from './routes/dashboard/settings'
import { Route as DashboardReportsRouteImport } from './routes/dashboard/reports'
import { Route as DashboardProfileRouteImport } from './routes/dashboard/profile'
import { Route as DashboardPayrollRouteImport } from './routes/dashboard/payroll'
import { Route as DashboardOrganogramRouteImport } from './routes/dashboard/organogram'
import { Route as DashboardNotificationsRouteImport } from './routes/dashboard/notifications'
import { Route as DashboardNominalRollRouteImport } from './routes/dashboard/nominal-roll'
import { Route as DashboardDocumentsRouteImport } from './routes/dashboard/documents'
import { Route as DashboardDepartmentsRouteImport } from './routes/dashboard/departments'
import { Route as DashboardChatRouteImport } from './routes/dashboard/chat'
import { Route as DashboardAttendanceRouteImport } from './routes/dashboard/attendance'
import { Route as DashboardAnnouncementsRouteImport } from './routes/dashboard/announcements'
import { Route as DashboardAllowancesRouteImport } from './routes/dashboard/allowances'
import { Route as DashboardAiAssistantRouteImport } from './routes/dashboard/ai-assistant'
import { Route as DashboardSettingsIndexRouteImport } from './routes/dashboard/settings/index'
import { Route as DashboardSettingsSecurityRouteImport } from './routes/dashboard/settings/security'
import { Route as DashboardSettingsRolesRouteImport } from './routes/dashboard/settings/roles'
import { Route as DashboardSettingsLoginPageRouteImport } from './routes/dashboard/settings/login-page'
import { Route as DashboardSettingsGeneralRouteImport } from './routes/dashboard/settings/general'
import { Route as DashboardSettingsExportRouteImport } from './routes/dashboard/settings/export'
import { Route as DashboardSettingsBrandingRouteImport } from './routes/dashboard/settings/branding'
import { Route as DashboardSettingsAuditLogsRouteImport } from './routes/dashboard/settings/audit-logs'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardIndexRoute = DashboardIndexRouteImport.update({
  id: '/dashboard/',
  path: '/dashboard/',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardStaffRoute = DashboardStaffRouteImport.update({
  id: '/dashboard/staff',
  path: '/dashboard/staff',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsRoute = DashboardSettingsRouteImport.update({
  id: '/dashboard/settings',
  path: '/dashboard/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardReportsRoute = DashboardReportsRouteImport.update({
  id: '/dashboard/reports',
  path: '/dashboard/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardProfileRoute = DashboardProfileRouteImport.update({
  id: '/dashboard/profile',
  path: '/dashboard/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardPayrollRoute = DashboardPayrollRouteImport.update({
  id: '/dashboard/payroll',
  path: '/dashboard/payroll',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardOrganogramRoute = DashboardOrganogramRouteImport.update({
  id: '/dashboard/organogram',
  path: '/dashboard/organogram',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNotificationsRoute = DashboardNotificationsRouteImport.update({
  id: '/dashboard/notifications',
  path: '/dashboard/notifications',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardNominalRollRoute = DashboardNominalRollRouteImport.update({
  id: '/dashboard/nominal-roll',
  path: '/dashboard/nominal-roll',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDocumentsRoute = DashboardDocumentsRouteImport.update({
  id: '/dashboard/documents',
  path: '/dashboard/documents',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardDepartmentsRoute = DashboardDepartmentsRouteImport.update({
  id: '/dashboard/departments',
  path: '/dashboard/departments',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardChatRoute = DashboardChatRouteImport.update({
  id: '/dashboard/chat',
  path: '/dashboard/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAttendanceRoute = DashboardAttendanceRouteImport.update({
  id: '/dashboard/attendance',
  path: '/dashboard/attendance',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAnnouncementsRoute = DashboardAnnouncementsRouteImport.update({
  id: '/dashboard/announcements',
  path: '/dashboard/announcements',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAllowancesRoute = DashboardAllowancesRouteImport.update({
  id: '/dashboard/allowances',
  path: '/dashboard/allowances',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardAiAssistantRoute = DashboardAiAssistantRouteImport.update({
  id: '/dashboard/ai-assistant',
  path: '/dashboard/ai-assistant',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardSettingsIndexRoute = DashboardSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsSecurityRoute =
  DashboardSettingsSecurityRouteImport.update({
    id: '/security',
    path: '/security',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsRolesRoute = DashboardSettingsRolesRouteImport.update({
  id: '/roles',
  path: '/roles',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsLoginPageRoute =
  DashboardSettingsLoginPageRouteImport.update({
    id: '/login-page',
    path: '/login-page',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsGeneralRoute =
  DashboardSettingsGeneralRouteImport.update({
    id: '/general',
    path: '/general',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsExportRoute = DashboardSettingsExportRouteImport.update({
  id: '/export',
  path: '/export',
  getParentRoute: () => DashboardSettingsRoute,
} as any)
const DashboardSettingsBrandingRoute =
  DashboardSettingsBrandingRouteImport.update({
    id: '/branding',
    path: '/branding',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)
const DashboardSettingsAuditLogsRoute =
  DashboardSettingsAuditLogsRouteImport.update({
    id: '/audit-logs',
    path: '/audit-logs',
    getParentRoute: () => DashboardSettingsRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/allowances': typeof DashboardAllowancesRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/nominal-roll': typeof DashboardNominalRollRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/organogram': typeof DashboardOrganogramRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/branding': typeof DashboardSettingsBrandingRoute
  '/dashboard/settings/export': typeof DashboardSettingsExportRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/login-page': typeof DashboardSettingsLoginPageRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/allowances': typeof DashboardAllowancesRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/nominal-roll': typeof DashboardNominalRollRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/organogram': typeof DashboardOrganogramRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard': typeof DashboardIndexRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/branding': typeof DashboardSettingsBrandingRoute
  '/dashboard/settings/export': typeof DashboardSettingsExportRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/login-page': typeof DashboardSettingsLoginPageRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings': typeof DashboardSettingsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/dashboard/ai-assistant': typeof DashboardAiAssistantRoute
  '/dashboard/allowances': typeof DashboardAllowancesRoute
  '/dashboard/announcements': typeof DashboardAnnouncementsRoute
  '/dashboard/attendance': typeof DashboardAttendanceRoute
  '/dashboard/chat': typeof DashboardChatRoute
  '/dashboard/departments': typeof DashboardDepartmentsRoute
  '/dashboard/documents': typeof DashboardDocumentsRoute
  '/dashboard/nominal-roll': typeof DashboardNominalRollRoute
  '/dashboard/notifications': typeof DashboardNotificationsRoute
  '/dashboard/organogram': typeof DashboardOrganogramRoute
  '/dashboard/payroll': typeof DashboardPayrollRoute
  '/dashboard/profile': typeof DashboardProfileRoute
  '/dashboard/reports': typeof DashboardReportsRoute
  '/dashboard/settings': typeof DashboardSettingsRouteWithChildren
  '/dashboard/staff': typeof DashboardStaffRoute
  '/dashboard/': typeof DashboardIndexRoute
  '/dashboard/settings/audit-logs': typeof DashboardSettingsAuditLogsRoute
  '/dashboard/settings/branding': typeof DashboardSettingsBrandingRoute
  '/dashboard/settings/export': typeof DashboardSettingsExportRoute
  '/dashboard/settings/general': typeof DashboardSettingsGeneralRoute
  '/dashboard/settings/login-page': typeof DashboardSettingsLoginPageRoute
  '/dashboard/settings/roles': typeof DashboardSettingsRolesRoute
  '/dashboard/settings/security': typeof DashboardSettingsSecurityRoute
  '/dashboard/settings/': typeof DashboardSettingsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/dashboard/ai-assistant'
    | '/dashboard/allowances'
    | '/dashboard/announcements'
    | '/dashboard/attendance'
    | '/dashboard/chat'
    | '/dashboard/departments'
    | '/dashboard/documents'
    | '/dashboard/nominal-roll'
    | '/dashboard/notifications'
    | '/dashboard/organogram'
    | '/dashboard/payroll'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/branding'
    | '/dashboard/settings/export'
    | '/dashboard/settings/general'
    | '/dashboard/settings/login-page'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/security'
    | '/dashboard/settings/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/dashboard/ai-assistant'
    | '/dashboard/allowances'
    | '/dashboard/announcements'
    | '/dashboard/attendance'
    | '/dashboard/chat'
    | '/dashboard/departments'
    | '/dashboard/documents'
    | '/dashboard/nominal-roll'
    | '/dashboard/notifications'
    | '/dashboard/organogram'
    | '/dashboard/payroll'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/staff'
    | '/dashboard'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/branding'
    | '/dashboard/settings/export'
    | '/dashboard/settings/general'
    | '/dashboard/settings/login-page'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/security'
    | '/dashboard/settings'
  id:
    | '__root__'
    | '/'
    | '/dashboard/ai-assistant'
    | '/dashboard/allowances'
    | '/dashboard/announcements'
    | '/dashboard/attendance'
    | '/dashboard/chat'
    | '/dashboard/departments'
    | '/dashboard/documents'
    | '/dashboard/nominal-roll'
    | '/dashboard/notifications'
    | '/dashboard/organogram'
    | '/dashboard/payroll'
    | '/dashboard/profile'
    | '/dashboard/reports'
    | '/dashboard/settings'
    | '/dashboard/staff'
    | '/dashboard/'
    | '/dashboard/settings/audit-logs'
    | '/dashboard/settings/branding'
    | '/dashboard/settings/export'
    | '/dashboard/settings/general'
    | '/dashboard/settings/login-page'
    | '/dashboard/settings/roles'
    | '/dashboard/settings/security'
    | '/dashboard/settings/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  DashboardAiAssistantRoute: typeof DashboardAiAssistantRoute
  DashboardAllowancesRoute: typeof DashboardAllowancesRoute
  DashboardAnnouncementsRoute: typeof DashboardAnnouncementsRoute
  DashboardAttendanceRoute: typeof DashboardAttendanceRoute
  DashboardChatRoute: typeof DashboardChatRoute
  DashboardDepartmentsRoute: typeof DashboardDepartmentsRoute
  DashboardDocumentsRoute: typeof DashboardDocumentsRoute
  DashboardNominalRollRoute: typeof DashboardNominalRollRoute
  DashboardNotificationsRoute: typeof DashboardNotificationsRoute
  DashboardOrganogramRoute: typeof DashboardOrganogramRoute
  DashboardPayrollRoute: typeof DashboardPayrollRoute
  DashboardProfileRoute: typeof DashboardProfileRoute
  DashboardReportsRoute: typeof DashboardReportsRoute
  DashboardSettingsRoute: typeof DashboardSettingsRouteWithChildren
  DashboardStaffRoute: typeof DashboardStaffRoute
  DashboardIndexRoute: typeof DashboardIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/': {
      id: '/dashboard/'
      path: '/dashboard'
      fullPath: '/dashboard/'
      preLoaderRoute: typeof DashboardIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/staff': {
      id: '/dashboard/staff'
      path: '/dashboard/staff'
      fullPath: '/dashboard/staff'
      preLoaderRoute: typeof DashboardStaffRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings': {
      id: '/dashboard/settings'
      path: '/dashboard/settings'
      fullPath: '/dashboard/settings'
      preLoaderRoute: typeof DashboardSettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/reports': {
      id: '/dashboard/reports'
      path: '/dashboard/reports'
      fullPath: '/dashboard/reports'
      preLoaderRoute: typeof DashboardReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/profile': {
      id: '/dashboard/profile'
      path: '/dashboard/profile'
      fullPath: '/dashboard/profile'
      preLoaderRoute: typeof DashboardProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/payroll': {
      id: '/dashboard/payroll'
      path: '/dashboard/payroll'
      fullPath: '/dashboard/payroll'
      preLoaderRoute: typeof DashboardPayrollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/organogram': {
      id: '/dashboard/organogram'
      path: '/dashboard/organogram'
      fullPath: '/dashboard/organogram'
      preLoaderRoute: typeof DashboardOrganogramRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/notifications': {
      id: '/dashboard/notifications'
      path: '/dashboard/notifications'
      fullPath: '/dashboard/notifications'
      preLoaderRoute: typeof DashboardNotificationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/nominal-roll': {
      id: '/dashboard/nominal-roll'
      path: '/dashboard/nominal-roll'
      fullPath: '/dashboard/nominal-roll'
      preLoaderRoute: typeof DashboardNominalRollRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/documents': {
      id: '/dashboard/documents'
      path: '/dashboard/documents'
      fullPath: '/dashboard/documents'
      preLoaderRoute: typeof DashboardDocumentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/departments': {
      id: '/dashboard/departments'
      path: '/dashboard/departments'
      fullPath: '/dashboard/departments'
      preLoaderRoute: typeof DashboardDepartmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/chat': {
      id: '/dashboard/chat'
      path: '/dashboard/chat'
      fullPath: '/dashboard/chat'
      preLoaderRoute: typeof DashboardChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/attendance': {
      id: '/dashboard/attendance'
      path: '/dashboard/attendance'
      fullPath: '/dashboard/attendance'
      preLoaderRoute: typeof DashboardAttendanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/announcements': {
      id: '/dashboard/announcements'
      path: '/dashboard/announcements'
      fullPath: '/dashboard/announcements'
      preLoaderRoute: typeof DashboardAnnouncementsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/allowances': {
      id: '/dashboard/allowances'
      path: '/dashboard/allowances'
      fullPath: '/dashboard/allowances'
      preLoaderRoute: typeof DashboardAllowancesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/ai-assistant': {
      id: '/dashboard/ai-assistant'
      path: '/dashboard/ai-assistant'
      fullPath: '/dashboard/ai-assistant'
      preLoaderRoute: typeof DashboardAiAssistantRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard/settings/': {
      id: '/dashboard/settings/'
      path: '/'
      fullPath: '/dashboard/settings/'
      preLoaderRoute: typeof DashboardSettingsIndexRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/security': {
      id: '/dashboard/settings/security'
      path: '/security'
      fullPath: '/dashboard/settings/security'
      preLoaderRoute: typeof DashboardSettingsSecurityRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/roles': {
      id: '/dashboard/settings/roles'
      path: '/roles'
      fullPath: '/dashboard/settings/roles'
      preLoaderRoute: typeof DashboardSettingsRolesRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/login-page': {
      id: '/dashboard/settings/login-page'
      path: '/login-page'
      fullPath: '/dashboard/settings/login-page'
      preLoaderRoute: typeof DashboardSettingsLoginPageRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/general': {
      id: '/dashboard/settings/general'
      path: '/general'
      fullPath: '/dashboard/settings/general'
      preLoaderRoute: typeof DashboardSettingsGeneralRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/export': {
      id: '/dashboard/settings/export'
      path: '/export'
      fullPath: '/dashboard/settings/export'
      preLoaderRoute: typeof DashboardSettingsExportRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/branding': {
      id: '/dashboard/settings/branding'
      path: '/branding'
      fullPath: '/dashboard/settings/branding'
      preLoaderRoute: typeof DashboardSettingsBrandingRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
    '/dashboard/settings/audit-logs': {
      id: '/dashboard/settings/audit-logs'
      path: '/audit-logs'
      fullPath: '/dashboard/settings/audit-logs'
      preLoaderRoute: typeof DashboardSettingsAuditLogsRouteImport
      parentRoute: typeof DashboardSettingsRoute
    }
  }
}

interface DashboardSettingsRouteChildren {
  DashboardSettingsAuditLogsRoute: typeof DashboardSettingsAuditLogsRoute
  DashboardSettingsBrandingRoute: typeof DashboardSettingsBrandingRoute
  DashboardSettingsExportRoute: typeof DashboardSettingsExportRoute
  DashboardSettingsGeneralRoute: typeof DashboardSettingsGeneralRoute
  DashboardSettingsLoginPageRoute: typeof DashboardSettingsLoginPageRoute
  DashboardSettingsRolesRoute: typeof DashboardSettingsRolesRoute
  DashboardSettingsSecurityRoute: typeof DashboardSettingsSecurityRoute
  DashboardSettingsIndexRoute: typeof DashboardSettingsIndexRoute
}

const DashboardSettingsRouteChildren: DashboardSettingsRouteChildren = {
  DashboardSettingsAuditLogsRoute: DashboardSettingsAuditLogsRoute,
  DashboardSettingsBrandingRoute: DashboardSettingsBrandingRoute,
  DashboardSettingsExportRoute: DashboardSettingsExportRoute,
  DashboardSettingsGeneralRoute: DashboardSettingsGeneralRoute,
  DashboardSettingsLoginPageRoute: DashboardSettingsLoginPageRoute,
  DashboardSettingsRolesRoute: DashboardSettingsRolesRoute,
  DashboardSettingsSecurityRoute: DashboardSettingsSecurityRoute,
  DashboardSettingsIndexRoute: DashboardSettingsIndexRoute,
}

const DashboardSettingsRouteWithChildren =
  DashboardSettingsRoute._addFileChildren(DashboardSettingsRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  DashboardAiAssistantRoute: DashboardAiAssistantRoute,
  DashboardAllowancesRoute: DashboardAllowancesRoute,
  DashboardAnnouncementsRoute: DashboardAnnouncementsRoute,
  DashboardAttendanceRoute: DashboardAttendanceRoute,
  DashboardChatRoute: DashboardChatRoute,
  DashboardDepartmentsRoute: DashboardDepartmentsRoute,
  DashboardDocumentsRoute: DashboardDocumentsRoute,
  DashboardNominalRollRoute: DashboardNominalRollRoute,
  DashboardNotificationsRoute: DashboardNotificationsRoute,
  DashboardOrganogramRoute: DashboardOrganogramRoute,
  DashboardPayrollRoute: DashboardPayrollRoute,
  DashboardProfileRoute: DashboardProfileRoute,
  DashboardReportsRoute: DashboardReportsRoute,
  DashboardSettingsRoute: DashboardSettingsRouteWithChildren,
  DashboardStaffRoute: DashboardStaffRoute,
  DashboardIndexRoute: DashboardIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
